
[MongoDB]
uri = "mongodb+srv://adhamalsahli90_db_user:sfVzMKXNgeQ1mrZ0@adham.j1syfjw.mongodb.net/?retryWrites=true&w=majority&appName=adham"
database = "IND320_assignment_2"
collection = "production_per_group_hour"
